import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/style/**/*.{js,ts,jsx,tsx,mdx,scss}",
  ],
  theme: {
    extend: {
      colors: {
        /* --- Legacy SG Colors (Keep for backward compatibility) --- */
        "sg-blue-bg": "var(--sg-blue-10)",
        "sg-blue-brdr": "var(--sg-blue-50)",
        "sg-green-bg": "var(--sg-green-10)",
        "sg-green-brdr": "var(--sg-green-50)",
        "sg-orange-bg": "var(--sg-orange-10)",
        "sg-orange-brdr": "var(--sg-orange-50)",
        "sg-gray-bg": "var(--sg-gray-10)",
        "sg-gray-brdr": "var(--sg-gray-50)",
        "sg-warn-bg": "#ffcccc",
        "sg-warn-fg": "red",
        "sg-text": "black",
        "sg-subtle": "#6b7280",
        "sg-selectable-bg": "var(--sg-just-off-white)",
        "sg-hovered-bg": "var(--sg-blue-10)",
        "sg-selected-bg": "var(--sg-blue-35)",
        "sg-body-bg": "var(--sg-just-off-white)",
        "sg-outOfBounds": "var(--sg-basement-gray)",

        /* --- New Semantic Palette (Mapped to CSS Variables) --- */
        text: {
          50: "var(--text-50)",
          100: "var(--text-100)",
          200: "var(--text-200)",
          300: "var(--text-300)",
          400: "var(--text-400)",
          500: "var(--text-500)",
          600: "var(--text-600)",
          700: "var(--text-700)",
          800: "var(--text-800)",
          900: "var(--text-900)",
          950: "var(--text-950)",
          DEFAULT: "var(--text-900)", // Default text color
        },
        background: {
          50: "var(--background-50)",
          100: "var(--background-100)",
          200: "var(--background-200)",
          300: "var(--background-300)",
          400: "var(--background-400)",
          500: "var(--background-500)",
          600: "var(--background-600)",
          700: "var(--background-700)",
          800: "var(--background-800)",
          900: "var(--background-900)",
          950: "var(--background-950)",
          DEFAULT: "var(--background-50)", // Default background
        },
        primary: {
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-900)",
          950: "var(--primary-950)",
          DEFAULT: "var(--primary-500)", // Main brand color
          foreground: "var(--primary-50)", // Text on primary
        },
        secondary: {
          50: "var(--secondary-50)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-900)",
          950: "var(--secondary-950)",
          DEFAULT: "var(--secondary-500)",
          foreground: "var(--secondary-50)",
        },
        accent: {
          50: "var(--accent-50)",
          100: "var(--accent-100)",
          200: "var(--accent-200)",
          300: "var(--accent-300)",
          400: "var(--accent-400)",
          500: "var(--accent-500)",
          600: "var(--accent-600)",
          700: "var(--accent-700)",
          800: "var(--accent-800)",
          900: "var(--accent-900)",
          950: "var(--accent-950)",
          DEFAULT: "var(--accent-500)",
          foreground: "var(--accent-50)",
        },
      },
    },
  },
  plugins: [],
};
export default config;
