"use client";

import { useState } from "react";
import { useSelector } from "react-redux";
import { useGlobalSettings } from "@/app/globalSettings/_lib/useGlobalSettings";
import { CardContent } from "@/style/components/card";
import { Input } from "@/style/components/input";
import { Label } from "@/style/components/label";
import { Button } from "@/style/components/button";
import { SaveButton, SaveStatus } from "@/components/SaveButton";
import { Separator } from "@/style/components/separator";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/style/components/select";
import { RadioGroup, RadioGroupItem } from "@/style/components/radio-group";
import { DatePicker } from "@/components/DatePicker";
import { DateRangePicker } from "@/components/DateRangePicker";
import { FormGroup } from "@/components/FormGroup";
import { singleCustSelect } from "@/app/realGreen/customer/selectors/singleCustSelect";
import { useSingleCustomer } from "@/app/realGreen/customer/hooks/useSingleCustomer";
import { priorityServiceCustomerActions } from "@/app/realGreen/customer/slices/customerSlices";
import { useAppDispatch } from "@/lib/hooks/redux";
import { priorityServiceSelect } from "@/app/priorityService/priorityServiceSelect";
import { usePriorityService } from "@/app/priorityService/usePriorityService";
import { PriorityServiceDoc } from "@/app/priorityService/PriorityServiceTypes";
import { TRange } from "@/lib/primatives/tRange/TRange";
import { Program } from "@/app/realGreen/customer/_lib/entities/types/ProgramTypes";
import { Service } from "@/app/realGreen/customer/_lib/entities/types/ServiceTypes";
import { getServiceStatuses } from "@/app/realGreen/_lib/subTypes/serviceStatus";
import { globalSettingsSelect } from "@/app/globalSettings/_lib/globalSettingsSelect";
import { QueryBuilder } from "@/app/realGreen/customer/mirror/QueryBuilder";
import { AppState } from "@/store";

const ELIGIBLE_STATUSES = getServiceStatuses(["active", "asap", "printed"]);

interface PriorityServiceFormProps {
  /** When provided, the form is in edit mode for this existing doc. */
  existingDoc?: PriorityServiceDoc;
  onDone: () => void;
}

export function PriorityServiceForm({
  existingDoc,
  onDone,
}: PriorityServiceFormProps) {
  useGlobalSettings({ autoLoad: true });

  const season = useSelector(globalSettingsSelect.season);

  // Build the single-customer plan for the form's customer lookup.
  // Season filters programs and services to the current season so the
  // dropdowns only show relevant options.
  const singleCustomerPlan = season
    ? new QueryBuilder()
        .addCustomerStep(["entity", "provider"], {
          stepName: "getCustomer",
          source: "values",
          filters: [] as [],  // custId injected by useSingleCustomer
          provides: { custId: true },
        })
        .addProgramStep(["entity", "provider"], {
          stepName: "getPrograms",
          source: "step",
          fromStep: "getCustomer",
          joinKey: "custId",
          filters: [{ field: "season", operator: "eq", value: season }],
          provides: { progId: true },
        })
        .addServiceStep(["entity"], {
          stepName: "getServices",
          source: "step",
          fromStep: "getPrograms",
          joinKey: "progId",
          filters: [{ field: "season", operator: "eq", value: season }],
        })
        .build()
    : [];

  const { lookup, clearCustomer } = useSingleCustomer({ mirrorQueryPlan: singleCustomerPlan });

  const dispatch = useAppDispatch();
  const { upsert, deleteOne } = usePriorityService();
  const priorityServiceMap = useSelector(priorityServiceSelect.priorityServiceMap);

  // Customer lookup state (create mode only)
  const [custIdInput, setCustIdInput] = useState("");
  const [selectedProgId, setSelectedProgId] = useState<number | null>(null);
  const [selectedServId, setSelectedServId] = useState<number | null>(
    existingDoc?.servId ?? null,
  );

  // Date mode
  const [dateMode, setDateMode] = useState<"single" | "range">(
    existingDoc?.dateRange ? "range" : "single",
  );
  const [singleDate, setSingleDate] = useState(existingDoc?.date ?? "");
  const [dateRange, setDateRange] = useState<TRange<string>>(
    existingDoc?.dateRange ?? { min: "", max: "" },
  );

  // Note
  const [note, setNote] = useState(existingDoc?.note ?? "");

  // Save state
  const [saveStatus, setSaveStatus] = useState<SaveStatus>("idle");
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  // Loaded customer from single context (reads from state.customer.single, not central)
  const customer = useSelector(singleCustSelect.customer);
  // Raw docs used to transfer single-customer data into the priorityService context on save.
  const singleRawDocs = useSelector(singleCustSelect.rawDocs);

  // Loading state for the customer lookup thunk.
  // Reads activeRequests directly because uiSelect.isLoadingType is generated by RTK's
  // selectors: field and expects the root state shape — see uiSliceEnhancementPlan.md.
  const isLookingUp = useSelector((state: AppState) =>
    state.ui.activeRequests.some((req) => req.startsWith("singleCustomer/getCustDocs-")),
  );

  const isEditMode = !!existingDoc;

  // Derive selected program and its services
  const selectedProgram: Program | null =
    customer?.programs.find((p) => p.progId === selectedProgId) ?? null;

  const eligibleServices: Service[] =
    selectedProgram?.services.filter((s) => ELIGIBLE_STATUSES.includes(s.status)) ?? [];

  // Auto-select service if only one eligible
  const resolvedServId: number | null = (() => {
    if (isEditMode) return existingDoc.servId;
    if (selectedServId !== null) return selectedServId;
    if (eligibleServices.length === 1) return eligibleServices[0].servId;
    return null;
  })();

  // Resolved service entity (for display fields on save)
  const resolvedService: Service | null =
    eligibleServices.find((s) => s.servId === resolvedServId) ?? null;

  // When a servId is resolved, check if there's already a doc for it (edit-in-create)
  const existingForServ = resolvedServId
    ? priorityServiceMap.get(resolvedServId)
    : null;

  const effectiveDoc = existingDoc ?? existingForServ;

  // Programs that have at least one eligible service (no point showing empty programs)
  const eligiblePrograms =
    customer?.programs.filter((program) =>
      program.services.some((s) => ELIGIBLE_STATUSES.includes(s.status)),
    ) ?? [];

  const parsedCustIdInput = parseInt(custIdInput, 10);
  const isAlreadyLoaded =
    !isNaN(parsedCustIdInput) &&
    parsedCustIdInput > 0 &&
    customer?.custId === parsedCustIdInput;

  const handleCustIdLoad = () => {
    if (!isNaN(parsedCustIdInput) && parsedCustIdInput > 0) {
      lookup(parsedCustIdInput);
      setSelectedProgId(null);
      setSelectedServId(null);
    }
  };

  const handleProgChange = (value: string) => {
    setSelectedProgId(parseInt(value, 10));
    setSelectedServId(null);
  };

  const handleServChange = (value: string) => {
    const servId = parseInt(value, 10);
    setSelectedServId(servId);

    // Pre-populate form if this servId already has a priority doc
    const existing = priorityServiceMap.get(servId);
    if (existing) {
      setDateMode(existing.dateRange ? "range" : "single");
      setSingleDate(existing.date ?? "");
      setDateRange(existing.dateRange ?? { min: "", max: "" });
      setNote(existing.note);
    }
  };

  const getEffectiveServId = (): number | null => {
    if (isEditMode) return existingDoc.servId;
    return resolvedServId;
  };

  const canSave = (): boolean => {
    const servId = getEffectiveServId();
    if (!servId) return false;
    if (dateMode === "single" && !singleDate) return false;
    if (dateMode === "range" && (!dateRange.min || !dateRange.max)) return false;
    return true;
  };

  const handleSave = async () => {
    const servId = getEffectiveServId();
    if (!servId || !canSave()) return;

    // Resolve display fields: from existing doc (edit) or from the selected service (create)
    const custDisplayName =
      effectiveDoc?.custDisplayName ??
      resolvedService?.program.customer.displayName ??
      "";
    const servCodeId =
      effectiveDoc?.servCodeId ??
      resolvedService?.servCode.servCodeId ??
      "";

    const doc: PriorityServiceDoc = {
      servId,
      note,
      custDisplayName,
      servCodeId,
      ...(dateMode === "single" ? { date: singleDate } : { dateRange }),
      createdAt: effectiveDoc?.createdAt ?? "",
      updatedAt: effectiveDoc?.updatedAt ?? "",
    };

    setSaveStatus("saving");
    await upsert(doc);

    // Transfer the single-customer docs into the priorityService context so the
    // left panel list hydrates immediately without waiting for a full reload.
    // centralCustomerSlice mirrors receiveBulk into the central Maps when the
    // "priorityService" context is active (set by useCustomerContext in page.tsx).
    if (!isEditMode && singleRawDocs.customerDocs.length > 0) {
      dispatch(
        priorityServiceCustomerActions.receiveBulk({
          customerDocs: singleRawDocs.customerDocs,
          programDocs: singleRawDocs.programDocs,
          serviceDocs: singleRawDocs.serviceDocs,
        }),
      );
    }

    setSaveStatus("success");
  };

  const handleSuccessComplete = () => {
    setSaveStatus("idle");
    if (!isEditMode && customer) {
      clearCustomer(customer.custId);
    }
    onDone();
  };

  const handleCancel = () => {
    if (!isEditMode && customer) {
      clearCustomer(customer.custId);
    }
    onDone();
  };

  const handleDelete = async () => {
    const servId = getEffectiveServId();
    if (!servId) return;
    await deleteOne(servId);
    onDone();
  };

  return (
    <CardContent className="pt-4">
      <div className="space-y-3">
        {/* ── Service Lookup (create mode only) ── */}
        {!isEditMode && (
          <>
            <FormGroup>
              <Label>Customer ID</Label>
              <div className="flex gap-2">
                <Input
                  type="number"
                  className="[appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                  placeholder="Enter customer ID"
                  value={custIdInput}
                  onChange={(e) => setCustIdInput(e.target.value)}
                />
                <Button
                  variant="primary"
                  intensity="solid"
                  onClick={handleCustIdLoad}
                  disabled={
                    isAlreadyLoaded ||
                    isLookingUp ||
                    isNaN(parsedCustIdInput) ||
                    parsedCustIdInput <= 0
                  }
                >
                  {isLookingUp ? "Loading…" : "Load"}
                </Button>
              </div>
            </FormGroup>

            <FormGroup>
              <Label>Program</Label>
              <Select
                value={selectedProgId?.toString() ?? ""}
                onValueChange={handleProgChange}
              >
                <SelectTrigger disabled={!customer || isLookingUp}>
                  <SelectValue placeholder="Select program…" />
                </SelectTrigger>
                <SelectContent>
                  {eligiblePrograms.map((program) => (
                    <SelectItem
                      key={program.progId}
                      value={program.progId.toString()}
                    >
                      {program.progCode.progCodeId}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </FormGroup>

            <FormGroup>
              <Label>Service</Label>
              <Select
                value={
                  resolvedServId !== null ? resolvedServId.toString() : ""
                }
                onValueChange={handleServChange}
              >
                <SelectTrigger disabled={!selectedProgram || isLookingUp}>
                  <SelectValue placeholder="Select service…" />
                </SelectTrigger>
                <SelectContent>
                  {eligibleServices.map((service) => (
                    <SelectItem
                      key={service.servId}
                      value={service.servId.toString()}
                    >
                      {service.servCode.servCodeId}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </FormGroup>

            <Separator />
          </>
        )}

        {/* ── Date ── */}
        <FormGroup>
          <Label>Date Type</Label>
          <RadioGroup
            variant="button-group"
            value={dateMode}
            onValueChange={(v) => setDateMode(v as "single" | "range")}
          >
            <RadioGroupItem value="single">Single Date</RadioGroupItem>
            <RadioGroupItem value="range">Date Range</RadioGroupItem>
          </RadioGroup>
        </FormGroup>

        {dateMode === "single" ? (
          <FormGroup>
            <Label>Date</Label>
            <DatePicker value={singleDate} onChange={setSingleDate} />
          </FormGroup>
        ) : (
          <FormGroup>
            <Label>Date Range</Label>
            <DateRangePicker value={dateRange} onChange={setDateRange} />
          </FormGroup>
        )}

        {/* ── Note ── */}
        <FormGroup>
          <Label>Note</Label>
          <textarea
            className="flex min-h-[80px] w-full rounded-md border border-input bg-card px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground/50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 resize-none"
            placeholder="Add a note for the production manager…"
            value={note}
            onChange={(e) => setNote(e.target.value)}
          />
        </FormGroup>

        {/* ── Actions ── */}
        <div className="flex gap-2 items-center">
          <SaveButton
            disabled={!canSave()}
            status={saveStatus}
            onClick={handleSave}
            onSuccessComplete={handleSuccessComplete}
          >
            Save
          </SaveButton>
          <Button variant="outline" onClick={handleCancel}>
            Cancel
          </Button>
        </div>

        {/* ── Delete (edit mode only) ── */}
        {isEditMode && (
          <>
            <Separator className="my-2" />
            {!showDeleteConfirm ? (
              <Button
                variant="destructive"
                intensity="soft"
                className="w-full"
                onClick={() => setShowDeleteConfirm(true)}
              >
                Remove Priority Flag
              </Button>
            ) : (
              <div className="space-y-2">
                <p className="text-xs text-muted-foreground">
                  Are you sure? This will remove the priority flag for this
                  service.
                </p>
                <div className="flex gap-2">
                  <Button
                    variant="destructive"
                    className="flex-1"
                    onClick={handleDelete}
                  >
                    Confirm Delete
                  </Button>
                  <Button
                    variant="outline"
                    className="flex-1"
                    onClick={() => setShowDeleteConfirm(false)}
                  >
                    Cancel
                  </Button>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </CardContent>
  );
}
