import { RGSearchBase } from "@/app/realGreen/customer/_lib/searchUtil/searchCriteria/types/RGSearchBase";
import { RGStringRange } from "@/app/realGreen/_lib/subTypes/RGSearchRanges";
import { TRange } from "@/lib/primatives/tRange/TRange";

export type ServiceSearchRaw = RGSearchBase & {
  searchType: "service";
  // asapDate?: DateTimeRange;
  // associationCode?: string;
  // callAhead?: number[];
  // called?: DateTimeRange;
  // // created?: DateTimeRange;
  // customerNote?: string;
  // customerNoteExpiration?: DateTimeRange;
  customerNumber?: number[];
  // discountAmount?: DecimalRange;
  // discountCode?: string;
  // endBefore?: IntRange;
  // estimatedManHour?: IntRange;
  // extraDescription?: string;
  id?: number[];
  // invoiceNumber?: number;
  // isDependentService?: boolean;
  // isPaid?: boolean;
  // isPromised?: boolean;
  // isReversed?: boolean;
  // manHourRate?: DecimalRange;
  // nextPrice?: DecimalRange;
  // nextSize?: DecimalRange;
  // // offset?: number;
  // posted?: DateTimeRange;
  // prepayAmount?: DecimalRange;
  // prepayId?: number;
  // price?: DecimalRange;
  // productionValue?: DecimalRange;
  // programDiscountAmount?: DecimalRange;
  programID?: number[];
  // // records?: number;
  // round?: IntRange;
  // scheduledTime?: IntRange;
  // serviceCode?: string[];
  serviceStatus?: string[];
  serviceYear?: number[];
  // size?: DecimalRange;
  // soldByOne?: string;
  // soldByTwo?: string;
  // soldDate?: DateTimeRange;
  // startAfter?: IntRange;
  startDate?: RGStringRange;
  // taxAmount1?: DecimalRange;
  // taxAmount2?: DecimalRange;
  // taxAmount3?: DecimalRange;
  // taxableAmount1?: DecimalRange;
  // taxableAmount2?: DecimalRange;
  // taxableAmount3?: DecimalRange;
  // technicianNote?: string;
  // technicianNoteExpiration?: DateTimeRange;
  // totalAmount?: DecimalRange;
  // // updated?: DateTimeRange;
};

export type ServiceSearchCriteria = {
  custIds?: number[];
  servIds?: number[];
  progIds?: number[];
  servStats?: string[];
  season: TRange<number>;
};
