import { CreatedUpdated } from "@/lib/mongoose/mongooseTypes";
import { Service } from "./ServiceTypes";
import { Customer } from "./CustomerTypes";
import { ProgCode } from "@/app/realGreen/progServ/_lib/types/ProgCodeTypes";
import { CallAhead } from "@/app/realGreen/callAhead/_lib/CallAheadTypes";
import { DiscountDoc } from "@/app/realGreen/discount/DiscountTypes";
import { ProgramUtils } from "@/app/realGreen/customer/_lib/classes/ProgramUtils";
import { SchedPromise } from "@/app/schedPromise/SchedPromiseTypes";

export type ProgramRaw = {
  averagePrice: number;
  // averageTime: number | null;
  billingType: string;
  callAhead: number | null;
  // callBackDate: string | null;
  // cancelCode: number | null;
  // cancelDate: string | null;
  // canceledBy: string;
  // confirmationDate: string | null;
  // confirmedBy: string;
  // contactDate: string | null;
  // contractId: number | null;
  // created: string;
  // customerLetterId: number | null;
  // customerNote: string;
  // customerNoteExpiration: string | null;
  customerNumber: number;
  dateSold: string;
  // dayCode: string;
  // difficulty: number;
  discountCodeId: string;
  // doneToDate: number;
  // endOn: string | null;
  // estimateAssignedDate: string | null;
  // estimateAssignedTo: string;
  // estimatedBy: string;
  // estimateGivenDate: string | null;
  // estimatePrintDate: string | null;
  // estimateReferredBy: number | null;
  // estimateRequestDate: string | null;
  // estimateRequestedBy: string;
  // estimateRequestTakenBy: string;
  // holdBeginDate: string | null;
  // holdCode: number | null;
  // holdDate: string | null;
  id: number;
  // includeInConfirmationLetter: boolean;
  // isAutoRenew: boolean;
  // isComplete: boolean;
  isFullProgram: boolean;
  // isNonServiceYear: boolean;
  // isProgram: boolean;
  // isRenewed: boolean;
  // isWorkOrder: boolean;
  lastPriceChange: string | null;
  // latestDependentServiceCompletionDate: string | null;
  // lockSchedule: boolean;
  // maximumRepetitions: number | null;
  nextDate: string | null;
  // numberOfServices: number | null;
  // paymentPlanByEmployee: string;
  // paymentPlanDate: string | null;
  price: number;
  programCode: string;
  programCodeId: number | null;
  // programDescription: string | null;
  // purchaseOrderNumber: string;
  // rejectionCode: number | null;
  // rejectionDate: string | null;
  // repeat: string | null;
  // repeatBy: string;
  // repeatEvery: number | null;
  // route: string;
  season: number;
  // sequence: number;
  // size: number;
  soldby1: string;
  soldby2: string;
  sourceCode: number;
  // standardPrice: number;
  // startYear: number | null;
  status: string;
  technicianNote: string;
  // technicianNoteExpiration: string | null;
  // temporaryDayCode: string;
  // temporaryRoute: string;
  temporarySequence: number;
  // updated: string;
  // workOrderPricing: number;
  // year: number | null;
};

export type ProgramCore = {
  avgPrice: number;
  billingType: string;
  callAheadId: number;
  custId: number;
  dateSold: string;
  discountId: string;
  progId: number;
  isFullProgram: boolean;
  lastPriceChange: string;
  nextDate: string;
  price: number;
  progDefId: number;
  season: number;
  soldBy: string[];
  sourceCodeId: number;
  status: string;
  techNote: string;
  tempSeq: number;
};

export type ProgramDocProps = CreatedUpdated & {
  progId: number;
};

export type ProgramDoc = ProgramCore & ProgramDocProps;

export type ProgramProps = {
  x: ProgramUtils;
  services: Service[];
  customer: Customer;
  progCode: ProgCode;
  callAhead: CallAhead | null;
  discount: DiscountDoc | null;
  promise: SchedPromise | null;
  promiseIssues: string[];
};

export type Program = ProgramDoc & ProgramProps;
