import { Customer } from "../types/CustomerTypes";
import { baseNumId } from "@/app/realGreen/_lib/realGreenConst";
import { baseAddress } from "@/app/realGreen/_lib/subTypes/Address";
import { baseContactPreference } from "@/app/realGreen/_lib/subTypes/ContactPreferences";
import { CustomerUtils } from "@/app/realGreen/customer/_lib/classes/CustomerUtils";
import { Aging, baseAgingParams } from "@/app/realGreen/customer/_lib/classes/Aging";

export const baseCustomerNoX: Omit<Customer, "x"> = {
  custId: baseNumId,
  address: baseAddress,
  billingAddress: baseAddress,
  billingCompanyName: "",
  billingEmail: "",
  billingFirstName: "",
  billingLastName: "",
  billingTitle: "",
  billingType: "",
  callAheadId: baseNumId,
  censusTractInfo: "",
  contactPreference: baseContactPreference,
  directions: "",
  discountId: "",
  displayName: "",
  email: "",
  importDate: "",
  isMasterAcct: false,
  lastName: "",
  masterAcctId: baseNumId,
  netBalance: 0,
  // phones: [],
  contactPoints: [],
  creditLimit: 0,
  due3: 0,
  remitBalance: 0,
  size: 0,
  status: "",
  holdCodeId: null,
  holdStart: null,
  holdEnd: null,
  subdivisionId: baseNumId,
  taxIds: [],
  taxCodes: [],
  taxRate: 0,
  techNote: "",
  useBilling: false,
  cancelCodeId: null,
  cancelDate: null,
  canceledBy: "",
  cardExpiryDate: null,
  cardType: "",
  companyName: "",
  creditHoldStatus: 0,
  doNotChargeInterest: false,
  doNotPutOnCreditHold: false,
  firstName: "",
  invoiceTypeId: 0,
  isBilledWithMasterAcct: false,
  isCanceled: false,
  cardLastFour: "",
  masterAcctBranches: [],
  memo: "",
  memoAlert: false,
  memoPayAlert: false,
  prepayBalance: 0,
  since: "",
  sizeSourceId: "",
  sizeUnitOfMeasureId: 0,
  sourceCodeId: 0,
  statementFrequency: 0,
  statementTypeId: 0,
  title: "",
  createdAt: "",
  updatedAt: "",
  programs: [],
  callLogs: [],
  callAhead: null,
  discount: null,
  flags: [],
  promise: null,
  promiseIssues: [],
  agingParams: baseAgingParams,
  aging: new Aging(baseAgingParams),
};

export const baseCustomer: Customer = {
  ...baseCustomerNoX,
  x: new CustomerUtils(baseCustomerNoX),
};