import mongoose from "mongoose";
import { createModel } from "@/lib/mongoose/createModel";
import { CustomerCore } from "@/app/realGreen/customer/_lib/entities/types/CustomerTypes";

const addressSchema = new mongoose.Schema(
  {
    addressLine1: String,
    addressLine2: String,
    addressLine3: String,
    city: String,
    countryCode: String,
    formattedAddress: { type: String, default: "" },
    formattedAddressWithCulture: { type: String, default: null },
    formattedZip: String,
    formattedZipWithCulture: { type: String, default: null },
    houseNumber: { type: String, default: "" },
    latitude: { type: Number, default: null },
    longitude: { type: Number, default: null },
    postDirection: { type: String, default: "" },
    preDirection: { type: String, default: "" },
    state: String,
    streetName: { type: String, default: "" },
    streetSuffix: { type: String, default: "" },
    zip: String,
  },
  { _id: false },
);

const contactPreferenceSchema = new mongoose.Schema(
  {
    autoPay: { type: Boolean, default: false },
    prefContactId: { type: String, default: "" },
    prefContactDesc: { type: String, default: "" },
    dontDirectMail: { type: Boolean, default: false },
    dontEmailInvoice: { type: Boolean, default: false },
    dontFollowUpEmail: { type: Boolean, default: false },
    dontKnock: { type: Boolean, default: false },
    dontText: { type: Boolean, default: false },
    dontUpsell: { type: Boolean, default: false },
    emailPrenotify: { type: Boolean, default: false },
    emailStatements: { type: Boolean, default: false },
    prefPhoneId: { type: String, default: "" },
    prefPhoneDesc: { type: String, default: "" },
    textPrenotify: { type: Boolean, default: true },
  },
  { _id: false },
);

const contactPointSchema = new mongoose.Schema(
  {
    point: { type: String, required: true },
    type: { type: String, required: true },
  },
  { _id: false },
);

const agingParamsSchema = new mongoose.Schema(
  {
    due1: { type: Number, default: 0 },
    due2: { type: Number, default: 0 },
    due3: { type: Number, default: 0 },
    due4: { type: Number, default: 0 },
    due5: { type: Number, default: 0 },
    due6: { type: Number, default: 0 },
    due7: { type: Number, default: 0 },
  },
  { _id: false },
);

const customerSchema = new mongoose.Schema<CustomerCore>(
  {
    custId: { type: Number, required: true, unique: true },
    address: { type: addressSchema, required: true },
    billingAddress: { type: addressSchema, required: true },
    billingCompanyName: { type: String, default: "" },
    billingEmail: { type: String, default: "" },
    billingFirstName: { type: String, default: "" },
    billingLastName: { type: String, default: "" },
    billingTitle: { type: String, default: "" },
    billingType: { type: String, default: "" },
    callAheadId: { type: Number, default: 0 },
    censusTractInfo: { type: String, default: "" },
    contactPreference: { type: contactPreferenceSchema, required: true },
    directions: { type: String, default: "" },
    discountId: { type: String, default: "" },
    displayName: { type: String, default: "" },
    email: { type: String, default: "" },
    importDate: { type: String, default: "" },
    isMasterAcct: { type: Boolean, default: false },
    lastName: { type: String, default: "" },
    masterAcctId: { type: Number, default: 0 },
    netBalance: { type: Number, default: 0 },
    contactPoints: { type: [contactPointSchema], default: [] },
    creditLimit: { type: Number, default: 0 },
    due3: { type: Number, default: 0 },
    agingParams: { type: agingParamsSchema, required: true },
    remitBalance: { type: Number, default: 0 },
    size: { type: Number, default: 0 },
    status: { type: String, default: "" },
    holdCodeId: { type: Number, default: null },
    holdStart: { type: String, default: null },
    holdEnd: { type: String, default: null },
    subdivisionId: { type: Number, default: 0 },
    taxIds: { type: [String], default: [] },
    techNote: { type: String, default: "" },
    useBilling: { type: Boolean, default: false },
    cancelCodeId: { type: Number, default: null },
    cancelDate: { type: String, default: null },
    canceledBy: { type: String, default: "" },
    cardExpiryDate: { type: String, default: null },
    cardType: { type: String, default: "" },
    companyName: { type: String, default: "" },
    creditHoldStatus: { type: Number, default: 0 },
    doNotChargeInterest: { type: Boolean, default: false },
    doNotPutOnCreditHold: { type: Boolean, default: false },
    firstName: { type: String, default: "" },
    invoiceTypeId: { type: Number, default: 0 },
    isBilledWithMasterAcct: { type: Boolean, default: false },
    isCanceled: { type: Boolean, default: false },
    cardLastFour: { type: String, default: "" },
    masterAcctBranches: { type: [Number], default: [] },
    memo: { type: String, default: "" },
    memoAlert: { type: Boolean, default: false },
    memoPayAlert: { type: Boolean, default: false },
    prepayBalance: { type: Number, default: 0 },
    since: { type: String, default: "" },
    sizeSourceId: { type: String, default: "" },
    sizeUnitOfMeasureId: { type: Number, default: 0 },
    sourceCodeId: { type: Number, default: 0 },
    statementFrequency: { type: Number, default: 0 },
    statementTypeId: { type: Number, default: 0 },
    title: { type: String, default: "" },
  },
  { timestamps: true },
);

export const CustomerModel = createModel<CustomerCore>("Customer", customerSchema);
