"use client";

import { useSelector } from "react-redux";
import { Info, TrendingUp } from "lucide-react";
import { customerValueSeasonSelect } from "@/app/bizPlan/customerValue/customerValueSeasonSelect";
import { retentionSelect } from "@/app/bizPlan/customerValue/retention/retentionSelect";
import { churnSelect } from "@/app/bizPlan/customerValue/retention/churnSelect";
import { Popover, PopoverContent, PopoverTrigger } from "@/style/components/popover";

export default function RetentionPage() {
  const allSeasons = useSelector(customerValueSeasonSelect.allSeasons);
  const historicalSeasons = useSelector(customerValueSeasonSelect.historicalSeasons);
  const customerRetentionRates = useSelector(retentionSelect.customerRetentionRates);
  const customerChurnDistribution = useSelector(churnSelect.customerChurnDistribution);
  const returnRateWithin2 = useSelector(churnSelect.customerReturnRateWithin2);

  const hasHistoricalData = historicalSeasons.length > 0 && customerRetentionRates.length > 0;

  return (
    <div className="flex flex-col h-full overflow-auto p-4 gap-6">
      {/* Header */}
      <div className="flex items-center gap-2 shrink-0">
        <TrendingUp className="h-4 w-4 text-muted-foreground" />
        <h2 className="text-sm font-semibold text-foreground">Retention Analysis</h2>
        <span className="text-xs text-muted-foreground">
          {allSeasons.length > 0
            ? `${allSeasons[0]} – ${allSeasons[allSeasons.length - 1]}`
            : "No seasons loaded"}
        </span>
        <Popover>
          <PopoverTrigger asChild>
            <button className="ml-1 text-muted-foreground hover:text-foreground transition-colors">
              <Info className="h-3.5 w-3.5" />
            </button>
          </PopoverTrigger>
          <PopoverContent className="w-96 max-h-[32rem] overflow-y-auto text-xs space-y-4" align="start">
            <div>
              <p className="font-semibold text-foreground mb-1">How these metrics are calculated</p>
              <p className="text-muted-foreground">
                All analysis is at the <strong>customer level</strong>. A customer is identified by
                their unique customer ID across seasons.
              </p>
            </div>

            <div>
              <p className="font-semibold text-foreground mb-1">Customer Retention by Season</p>
              <p className="text-muted-foreground mb-2">
                Each column represents a transition from one season to the next (e.g., 2023 → 2024).
              </p>
              <ul className="space-y-1.5 text-muted-foreground">
                <li>
                  <span className="font-medium text-foreground">Prior Count</span> — the number of
                  unique customers who had at least one active service in the earlier season.
                </li>
                <li>
                  <span className="font-medium text-foreground">Retained</span> — how many of those
                  prior customers also appear in the next season. The percentage is retained ÷ prior.
                </li>
                <li>
                  <span className="font-medium text-foreground">Prior Revenue</span> — the total
                  revenue generated by all prior-season customers, using each service&apos;s price
                  after discounts.
                </li>
                <li>
                  <span className="font-medium text-foreground">Retained Revenue</span> — the prior
                  season&apos;s revenue attributable only to customers who were retained. This shows
                  how much of last season&apos;s revenue base carried forward.
                </li>
              </ul>
            </div>

            <div>
              <p className="font-semibold text-foreground mb-1">
                Churn Analysis — Customers Who Returned
              </p>
              <p className="text-muted-foreground mb-2">
                This table only counts customers who left <em>and eventually came back</em>. It does
                not include customers who left permanently.
              </p>
              <ul className="space-y-1.5 text-muted-foreground">
                <li>
                  <span className="font-medium text-foreground">Absent For N seasons</span> — the
                  customer was missing for exactly N consecutive seasons between two active seasons.
                  For example, &ldquo;2 seasons&rdquo; means they were active in 2022, gone in 2023
                  and 2024, then returned in 2025.
                </li>
                <li>
                  <span className="font-medium text-foreground">Returned</span> — the count of
                  customers who fit that exact absence pattern.
                </li>
                <li>
                  <span className="font-medium text-foreground">Revenue Recovered</span> — the
                  revenue those customers generated in their first season back.
                </li>
              </ul>
            </div>

            <div>
              <p className="font-semibold text-foreground mb-1">Return Rate Narrative</p>
              <p className="text-muted-foreground">
                Of all customers who were absent in at least one season, this is the percentage who
                returned within 2 seasons — regardless of how long they were ultimately gone. A
                customer counts as &ldquo;returned within 2&rdquo; if there is any gap in their
                history where they came back after being away for 1 or 2 seasons.
              </p>
            </div>
          </PopoverContent>
        </Popover>
      </div>

      {!hasHistoricalData ? (
        <div className="flex flex-col items-center justify-center flex-1 gap-3 text-center">
          <TrendingUp className="h-10 w-10 text-muted-foreground/40" />
          <p className="text-sm text-muted-foreground">
            No historical data loaded yet.
          </p>
          <p className="text-xs text-muted-foreground">
            Use &ldquo;Load via API&rdquo; or &ldquo;Load JSON&rdquo; in the header to load data.
          </p>
        </div>
      ) : (
        <>
          {/* Narrative stat */}
          {returnRateWithin2 > 0 && (
            <div className="bg-accent/10 border border-border rounded-md px-4 py-3 shrink-0">
              <p className="text-sm font-semibold text-foreground">
                {(returnRateWithin2 * 100).toFixed(0)}% of customers who cancel return within 2
                seasons.
              </p>
            </div>
          )}

          {/* Retention table */}
          <div className="shrink-0">
            <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">
              Customer Retention by Season
            </h3>
            <div className="overflow-x-auto">
              <table className="text-sm w-full border-collapse">
                <thead>
                  <tr className="border-b border-border">
                    <th className="text-left py-2 pr-4 text-muted-foreground font-medium text-xs">
                      Metric
                    </th>
                    {customerRetentionRates.map((rate) => (
                      <th
                        key={rate.toSeason}
                        className="text-right py-2 px-3 text-muted-foreground font-medium text-xs"
                      >
                        {rate.fromSeason} → {rate.toSeason}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-border/50">
                    <td className="py-2 pr-4 text-xs text-muted-foreground">Prior Count</td>
                    {customerRetentionRates.map((rate) => (
                      <td key={rate.toSeason} className="text-right py-2 px-3 text-xs">
                        {rate.priorCount.toLocaleString()}
                      </td>
                    ))}
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-2 pr-4 text-xs text-muted-foreground">Retained</td>
                    {customerRetentionRates.map((rate) => (
                      <td key={rate.toSeason} className="text-right py-2 px-3 text-xs">
                        {rate.retainedCount.toLocaleString()}{" "}
                        <span className="text-muted-foreground">
                          ({(rate.rate * 100).toFixed(1)}%)
                        </span>
                      </td>
                    ))}
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-2 pr-4 text-xs text-muted-foreground">Prior Revenue</td>
                    {customerRetentionRates.map((rate) => (
                      <td key={rate.toSeason} className="text-right py-2 px-3 text-xs">
                        ${Math.round(rate.priorRevenue).toLocaleString()}
                      </td>
                    ))}
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-xs text-muted-foreground">Retained Revenue</td>
                    {customerRetentionRates.map((rate) => (
                      <td key={rate.toSeason} className="text-right py-2 px-3 text-xs">
                        ${Math.round(rate.retainedRevenue).toLocaleString()}{" "}
                        <span className="text-muted-foreground">
                          ({(rate.revenueRate * 100).toFixed(1)}%)
                        </span>
                      </td>
                    ))}
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Churn distribution */}
          <div className="shrink-0">
            <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">
              Churn Analysis — Customers Who Returned
            </h3>
            <div className="overflow-x-auto">
              <table className="text-sm w-full border-collapse">
                <thead>
                  <tr className="border-b border-border">
                    <th className="text-left py-2 pr-4 text-muted-foreground font-medium text-xs">
                      Absent For
                    </th>
                    <th className="text-right py-2 px-3 text-muted-foreground font-medium text-xs">
                      Returned
                    </th>
                    <th className="text-right py-2 px-3 text-muted-foreground font-medium text-xs">
                      Revenue Recovered
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {customerChurnDistribution.map((row) => (
                    <tr key={row.absenceLength} className="border-b border-border/50">
                      <td className="py-2 pr-4 text-xs text-muted-foreground">{row.label}</td>
                      <td className="text-right py-2 px-3 text-xs">
                        {row.count.toLocaleString()}
                      </td>
                      <td className="text-right py-2 px-3 text-xs">
                        ${Math.round(row.revenueRecovered).toLocaleString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
